build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                environment:
                    php:
                        version: 7.2
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
        tests: true
filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php: {  }

